{
 "title": "Postgres Instance Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Dead tuples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup",
     "legendFormat": "db={{datname}} table={{relname}}"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pg_stat_database_numbackends", "legendFormat": "db={{datname}}" }
   ]
  },
  {
   "title": "IO usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(pg_stat_io[1m])", "legendFormat": "{{process}} {{operation}}" }
   ]
  },
  {
   "title": "User defined indexes size in MB",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_index_size / 1000000",
     "legendFormat": "{{index_name}}"
    }
   ]
  },
  {
   "title": "User defined table size in MB",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_table_size / 1000000",
     "legendFormat": "{{table_name}}"
    }
   ]
  }
 ]
}